version: "3.8"
services:
  backend:
    image: $CI_REGISTRY_IMAGE:$DOCKER_TAG
    ports:
      - "8080:8080"
  postgres:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  postgres-data: